-- Restrict "any signed-in user" policies to internal team members (users with a role).
ALTER POLICY "auth_read_log" ON public.agent_activity_log USING (public.is_internal_user(auth.uid()));
ALTER POLICY "auth_read_status" ON public.agent_status USING (public.is_internal_user(auth.uid()));
ALTER POLICY "auth_read_agents" ON public.ai_agents USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can read app_roles" ON public.app_roles USING (public.is_internal_user(auth.uid()));
ALTER POLICY "auth_read_queue" ON public.ceo_approval_queue USING (public.is_internal_user(auth.uid()));
ALTER POLICY "auth read fse_drive_index" ON public.fse_drive_index USING (public.is_internal_user(auth.uid()));
ALTER POLICY "authenticated read flags" ON public.fse_supplier_flags USING (public.is_internal_user(auth.uid()));
ALTER POLICY "authenticated update flags" ON public.fse_supplier_flags USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can read fse sync state" ON public.fse_sync_state USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated users can manage item_notes" ON public.item_notes USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "ops_actions_auth_all" ON public.ops_actions USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "ops_bookings_auth_all" ON public.ops_bookings USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view partner files" ON public.partner_files USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view partner links" ON public.partner_links USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view partner services" ON public.partner_services USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view partners" ON public.partners USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can read permissions" ON public.permissions USING (public.is_internal_user(auth.uid()));
ALTER POLICY "votes readable by team" ON public.platform_feedback_votes USING (public.is_internal_user(auth.uid()));
ALTER POLICY "auth_read_product_types" ON public.product_types USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view products" ON public.products USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view files" ON public.supplier_files USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view links" ON public.supplier_links USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view supplier scores" ON public.supplier_scores USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view services" ON public.supplier_services USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can view suppliers" ON public.suppliers USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated users can view settings" ON public.system_settings USING (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can manage itineraries" ON public.itineraries USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can manage itinerary days" ON public.itinerary_days USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can manage events" ON public.proposal_events USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));
ALTER POLICY "Authenticated can manage used_photos" ON public.used_photos USING (public.is_internal_user(auth.uid())) WITH CHECK (public.is_internal_user(auth.uid()));