// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-leads.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List leads (sales pipeline) for the signed-in user, newest activity first. Optionally filter by status or destination.",
  inputSchema: {
    status: z.string().optional().describe("Filter by lead status, e.g. novo, proposta, ganho."),
    destination: z.string().optional().describe("Case-insensitive partial match on destination."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, destination, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select(
      "id,lead_code,yt_id,client_name,email,status,destination,travel_dates,travel_end_date,pax,number_of_days,budget_level,sales_owner,updated_at"
    ).order("updated_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (destination) query = query.ilike("destination", `%${destination}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, leads: data ?? [] }, null, 2) }],
      structuredContent: { total: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead detail",
  description: "Get a single lead with its planner and costing data. Look it up by lead id (uuid) or by lead code such as YT-2026-0001.",
  inputSchema: {
    lead_id: z2.string().optional().describe("Lead uuid."),
    lead_code: z2.string().optional().describe("Lead code, e.g. YT-2026-0001.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, lead_code }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    if (!lead_id && !lead_code) throw new ToolError2("Provide lead_id or lead_code");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("*").limit(1);
    query = lead_id ? query.eq("id", lead_id) : query.eq("lead_code", lead_code);
    const { data, error } = await query.maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2("Lead not found");
    const [planner, costing] = await Promise.all([
      supabase.from("lead_planner_data").select("*").eq("lead_id", data.id).eq("version", data.active_version ?? 0).order("day_number"),
      supabase.from("lead_costing_data").select("*").eq("lead_id", data.id).eq("version", data.active_version ?? 0).order("day_number")
    ]);
    const payload = { lead: data, planner: planner.data ?? null, costing: costing.data ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-upcoming-trips.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_upcoming_trips_default = defineTool3({
  name: "list_upcoming_trips",
  title: "List upcoming trips",
  description: "List confirmed trips departing within the next N days, soonest first. Use for operational priorities (D-1, D-3, D-7).",
  inputSchema: {
    days: z3.number().int().optional().describe("Days ahead to include (default 7, max 365)."),
    limit: z3.number().int().optional().describe("Max rows to return (default 50, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const window = Math.min(Math.max(days ?? 7, 1), 365);
    const take = Math.min(Math.max(limit ?? 50, 1), 100);
    const from = /* @__PURE__ */ new Date();
    const until = /* @__PURE__ */ new Date();
    until.setDate(until.getDate() + window);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trips").select(
      "id,trip_code,client_name,destination,start_date,end_date,status,pax,total_value,urgency,has_blocker,blocker_note,sales_owner,lead_id"
    ).gte("start_date", from.toISOString().slice(0, 10)).lte("start_date", until.toISOString().slice(0, 10)).order("start_date", { ascending: true }).limit(take);
    if (error) throw new ToolError3(error.message);
    const payload = { days_ahead: window, total: data?.length ?? 0, trips: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List operational and sales tasks, optionally filtered by status, team or lead.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by task status, e.g. todo, doing, done."),
    team: z4.string().optional().describe("Filter by team, e.g. sales or ops."),
    lead_id: z4.string().optional().describe("Only tasks linked to this lead uuid."),
    limit: z4.number().int().optional().describe("Max rows to return (default 50, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, team, lead_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const take = Math.min(Math.max(limit ?? 50, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("tasks").select("id,title,description,status,priority,team,category,due_date,lead_id,trip_id,assigned_to,updated_at").order("due_date", { ascending: true, nullsFirst: false }).limit(take);
    if (status) query = query.eq("status", status);
    if (team) query = query.eq("team", team);
    if (lead_id) query = query.eq("lead_id", lead_id);
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    const payload = { total: data?.length ?? 0, tasks: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_task_default = defineTool5({
  name: "create_task",
  title: "Create task",
  description: "Create an operational or sales task for the signed-in user. Keep titles short and actionable.",
  inputSchema: {
    title: z5.string().trim().describe("Short actionable title."),
    description: z5.string().optional().describe("Optional details."),
    team: z5.string().optional().describe("Team, e.g. sales or ops."),
    priority: z5.string().optional().describe("Priority, e.g. low, medium, high, urgent."),
    due_date: z5.string().optional().describe("Due date as YYYY-MM-DD."),
    lead_id: z5.string().optional().describe("Link to this lead uuid."),
    trip_id: z5.string().optional().describe("Link to this trip uuid.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, team, priority, due_date, lead_id, trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    if (!title.trim()) throw new ToolError5("title is required");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      title: title.trim(),
      description: description ?? null,
      team: team ?? null,
      priority: priority ?? null,
      due_date: due_date ?? null,
      lead_id: lead_id ?? null,
      trip_id: trip_id ?? null,
      created_by: ctx.getUserId()
    }).select().single();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ created: true, task: data }, null, 2) }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jufqscczzmioauzkqztj";
var mcp_default = defineMcp({
  name: "your-travel-2-0",
  title: "Your Travel 2.0",
  version: "0.1.0",
  instructions: "Operations tools for Your Tours Portugal. Use `list_leads` and `get_lead` for the sales pipeline, `list_upcoming_trips` for departures needing attention, and `list_tasks` / `create_task` for operational follow-up. All data is scoped to the signed-in user's access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, list_upcoming_trips_default, list_tasks_default, create_task_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
