-- ─── AGENT NOTIFICATIONS ───────────────────────────────────────────────────
-- Alerts and notifications generated by AI agents (Spark / MCP)
create table if not exists agent_notifications (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz default now(),
  type          text not null check (type in ('alert','info','warning','action_required')),
  priority      text default 'medium' check (priority in ('low','medium','high','urgent')),
  title         text not null,
  body          text not null,
  entity_type   text,          -- 'lead' | 'booking' | 'proposal' | 'payment' | 'invoice'
  entity_id     uuid,
  entity_ref    text,          -- human-readable e.g. "Smith Family - Algarve Jun 2026"
  agent_name    text default 'spark',
  read_at       timestamptz,
  dismissed_at  timestamptz,
  metadata      jsonb default '{}'
);

-- ─── AGENT PENDING ACTIONS ──────────────────────────────────────────────────
-- Actions proposed by AI agents, requiring human approval before execution
create table if not exists agent_pending_actions (
  id            uuid primary key default gen_random_uuid(),
  created_at    timestamptz default now(),
  action_type   text not null,  -- 'send_email' | 'update_status' | 'create_calendar_event' | 'request_invoice' | 'send_proposal_followup'
  title         text not null,
  description   text not null,
  entity_type   text,
  entity_id     uuid,
  entity_ref    text,
  agent_name    text default 'spark',
  status        text default 'pending' check (status in ('pending','approved','rejected','executed','failed')),
  approved_by   uuid references auth.users(id),
  approved_at   timestamptz,
  executed_at   timestamptz,
  rejected_at   timestamptz,
  rejection_reason text,
  payload       jsonb default '{}',  -- email content, event details, etc.
  result        jsonb default '{}'   -- execution result
);

-- ─── RLS ────────────────────────────────────────────────────────────────────
alter table agent_notifications   enable row level security;
alter table agent_pending_actions enable row level security;

create policy "team can read notifications"
  on agent_notifications for select to authenticated using (true);

create policy "team can update notifications"
  on agent_notifications for update to authenticated using (true);

create policy "service role can insert notifications"
  on agent_notifications for insert to service_role with check (true);

create policy "team can read pending actions"
  on agent_pending_actions for select to authenticated using (true);

create policy "team can update pending actions"
  on agent_pending_actions for update to authenticated using (true);

create policy "service role can insert pending actions"
  on agent_pending_actions for insert to service_role with check (true);

-- ─── SEED: demo notifications so the UI isn't empty ────────────────────────
insert into agent_notifications (type, priority, title, body, entity_type, entity_ref, agent_name) values
  ('action_required', 'high',   'Proposta sem resposta há 6 dias',       'O cliente Johnson Family não respondeu à proposta enviada a 17 Mai. Recomendar follow-up.', 'proposal', 'Johnson Family — Douro Jun 2026', 'spark'),
  ('warning',         'medium', 'Fatura em falta — FSE Transporte',      'A fatura da Viagens ABC referente ao transfer de 14 Jun ainda não foi recebida (prazo era 20 Mai).', 'invoice', 'Transfer Faro Airport — 14 Jun', 'spark'),
  ('alert',           'urgent', 'Confirmação pendente — Quinta do Lago', 'O hotel Quinta do Lago ainda não confirmou a reserva de 5 noites (check-in 28 Jun). Faltam 35 dias.', 'booking', 'Smith Family — Algarve Jun 2026', 'spark'),
  ('info',            'low',    'Calendário actualizado automaticamente', '3 eventos sincronizados com Google Calendar com base nas confirmações recebidas hoje.', null, null, 'spark');

insert into agent_pending_actions (action_type, title, description, entity_type, entity_ref, payload) values
  ('send_email', 'Follow-up — Johnson Family', 'Enviar email de seguimento à proposta Douro Jun 2026, não respondida há 6 dias.', 'proposal', 'Johnson Family — Douro Jun 2026',
    '{"to": "johnson@email.com", "subject": "A sua proposta Your Tours Portugal — Douro Valley", "body_preview": "Olá, gostaríamos de saber se tiveram oportunidade de rever a proposta..."}'::jsonb),
  ('send_email', 'Solicitar fatura — Viagens ABC', 'Solicitar fatura em falta ao fornecedor Viagens ABC (transfer 14 Jun).', 'invoice', 'Viagens ABC — Transfer Jun 2026',
    '{"to": "faturas@viagensabc.pt", "subject": "Pedido de fatura — Transfer 14 Jun 2026", "body_preview": "Exmos. Srs., venho por este meio solicitar o envio da fatura referente ao serviço..."}'::jsonb);
